import type { AppState } from "./types";

const now = new Date("2026-04-25T09:00:00.000Z").toISOString();

export function createInitialState(): AppState {
  return {
    organizations: [
      {
        id: "org_kernel_guard",
        name: "KernelGuard StockOps",
        slug: "kernelguard",
      },
    ],
    users: [
      {
        id: "usr_owner",
        name: "Eren Admin",
        email: "eren@example.com",
        passwordHash:
          "scrypt$73746f636b6f70732d64656d6f2d73616c74$fc998ce1d571436fec3ff1bff4ef00c35fb790679c0f54ef89f66d94e3fe80bec732535eeb1a30cb8cd0114f2cc07587a8e51b716de1815bf878ade3b8e3ed43",
      },
    ],
    memberships: [
      {
        organizationId: "org_kernel_guard",
        userId: "usr_owner",
        role: "Owner",
      },
    ],
    warehouses: [
      {
        id: "wh_main",
        organizationId: "org_kernel_guard",
        code: "MAIN",
        name: "Ana Depo",
        isDefault: true,
      },
      {
        id: "wh_showroom",
        organizationId: "org_kernel_guard",
        code: "SHOW",
        name: "Showroom",
        isDefault: false,
      },
    ],
    products: [
      {
        id: "prd_kbd_mx",
        organizationId: "org_kernel_guard",
        sku: "KBD-MX-001",
        name: "Mekanik Klavye MX",
        barcode: "8690000000011",
        category: "Aksesuar",
        minimumStock: 12,
        isActive: true,
        unitPrice: 0,
      },
      {
        id: "prd_mouse_wireless",
        organizationId: "org_kernel_guard",
        sku: "MOU-WL-002",
        name: "Kablosuz Mouse",
        barcode: "8690000000028",
        category: "Aksesuar",
        minimumStock: 20,
        isActive: true,
        unitPrice: 0,
      },
      {
        id: "prd_monitor_27",
        organizationId: "org_kernel_guard",
        sku: "MON-27-4K",
        name: "27 inç 4K Monitör",
        barcode: "8690000000035",
        category: "Ekran",
        minimumStock: 8,
        isActive: true,
        unitPrice: 0,
      },
    ],
    suppliers: [
      {
        id: "sup_techline",
        organizationId: "org_kernel_guard",
        name: "TechLine Tedarik",
        contactName: "Ayşe Demir",
        email: "satis@techline.test",
        phone: "+90 212 000 00 00",
        leadTimeDays: 5,
        productIds: ["prd_kbd_mx", "prd_mouse_wireless"],
      },
      {
        id: "sup_displayhub",
        organizationId: "org_kernel_guard",
        name: "DisplayHub",
        contactName: "Mert Kaya",
        email: "orders@displayhub.test",
        phone: "+90 216 000 00 00",
        leadTimeDays: 9,
        productIds: ["prd_monitor_27"],
      },
    ],
    stockMovements: [
      {
        id: "mov_1",
        organizationId: "org_kernel_guard",
        warehouseId: "wh_main",
        productId: "prd_kbd_mx",
        type: "INBOUND",
        quantityChange: 30,
        reference: "OPENING",
        note: "Açılış stoğu",
        createdById: "usr_owner",
        createdAt: now,
      },
      {
        id: "mov_2",
        organizationId: "org_kernel_guard",
        warehouseId: "wh_main",
        productId: "prd_mouse_wireless",
        type: "INBOUND",
        quantityChange: 16,
        reference: "OPENING",
        note: "Açılış stoğu",
        createdById: "usr_owner",
        createdAt: now,
      },
      {
        id: "mov_3",
        organizationId: "org_kernel_guard",
        warehouseId: "wh_main",
        productId: "prd_monitor_27",
        type: "INBOUND",
        quantityChange: 6,
        reference: "OPENING",
        note: "Açılış stoğu",
        createdById: "usr_owner",
        createdAt: now,
      },
      {
        id: "mov_4",
        organizationId: "org_kernel_guard",
        warehouseId: "wh_showroom",
        productId: "prd_kbd_mx",
        type: "INBOUND",
        quantityChange: 4,
        reference: "TRANSFER",
        note: "Showroom teşhir",
        createdById: "usr_owner",
        createdAt: now,
      },
    ],
    salesOrders: [
      {
        id: "so_1001",
        organizationId: "org_kernel_guard",
        code: "SO-1001",
        customerName: "Nova Bilişim",
        status: "DRAFT",
        lines: [{ productId: "prd_kbd_mx", quantity: 3 }],
        createdAt: now,
      },
      {
        id: "so_1002",
        organizationId: "org_kernel_guard",
        code: "SO-1002",
        customerName: "Mavi Ofis",
        status: "CONFIRMED",
        lines: [{ productId: "prd_mouse_wireless", quantity: 4 }],
        createdAt: now,
      },
    ],
    purchaseOrders: [
      {
        id: "po_2001",
        organizationId: "org_kernel_guard",
        code: "PO-2001",
        supplierId: "sup_displayhub",
        status: "SENT",
        expectedDate: "2026-05-02",
        lines: [{ productId: "prd_monitor_27", quantity: 10, receivedQuantity: 0 }],
        createdAt: now,
      },
    ],
    auditLogs: [
      {
        id: "aud_1",
        organizationId: "org_kernel_guard",
        actorId: "usr_owner",
        action: "CREATE",
        entityType: "Organization",
        entityId: "org_kernel_guard",
        summary: "Demo organizasyon oluşturuldu",
        createdAt: now,
      },
    ],
    sessions: [],
    webhookEvents: [],
    notificationDeliveries: [],
    customers: [],
    invoices: [],
  };
}
